import assert from 'node:assert/strict';
import {iniciarServidor,lancarNavegador} from './_infra.mjs';
const {srv,url}=await iniciarServidor(process.cwd(),+(process.env.CT_PORT||9400));const {browser,motor}=await lancarNavegador();
try {const p=await browser.newPage();await p.goto(url+'/__semente');await p.evaluate(()=>{localStorage.clear();localStorage.setItem('catedra:auth','1');localStorage.setItem('catedra:onboarded','1');});await p.goto(url+'/Catedra.dc.html');await p.waitForFunction(()=>window.__catedraApp);
for(const width of [390,1280]){await p.setViewportSize({width,height:844});await p.waitForFunction(()=>window.__catedraApp.state.isMobile===(innerWidth<900));await p.evaluate(()=>window.__catedraApp.setState({menuOpen:true}));const aside=p.locator('aside');const names=await aside.locator('button[data-view]').allTextContents();assert.equal(names.findIndex(x=>x.trim()==='Registrar Raio X'),names.findIndex(x=>x.trim()==='Ciclo de Estudos')+1);await aside.getByText('Fases do concurso',{exact:true}).waitFor();
await aside.getByRole('button',{name:'Registrar Raio X',exact:true}).click();await p.getByText('Raio-X do simulado',{exact:true}).waitFor();assert.equal(await p.getByRole('button',{name:'Treinar 1ª fase',exact:true}).count(),0);assert.equal(await p.getByText('Fazer simulado agora',{exact:true}).count(),0);assert.equal(await aside.getByRole('button',{name:'Registrar Raio X',exact:true}).getAttribute('aria-current'),'page');
await p.evaluate(()=>window.__catedraApp.setState({menuOpen:true}));await aside.getByRole('button',{name:'Fase Objetiva',exact:true}).click();await p.getByText('Fazer simulado agora',{exact:true}).waitFor();assert.equal(await p.getByText('Raio-X do simulado',{exact:true}).count(),0);assert.equal(await aside.getByRole('button',{name:'Fase Objetiva',exact:true}).getAttribute('aria-current'),'page');assert.equal(await aside.getByRole('button',{name:'Registrar Raio X',exact:true}).getAttribute('aria-current'),'false');
await p.evaluate(()=>window.__catedraApp.setState({menuOpen:true}));await aside.getByRole('button',{name:'Fase Discursiva',exact:true}).click();await p.getByRole('navigation',{name:'Fase Discursiva',exact:true}).waitFor();await p.getByRole('button',{name:'Provas oficiais',exact:true}).click();assert.equal(await p.evaluate(()=>window.__catedraApp.state.view),'segundafase');
await p.evaluate(()=>window.__catedraApp.setState({menuOpen:true}));await aside.getByRole('button',{name:'Fase Oral',exact:true}).click();assert.equal(await p.evaluate(()=>window.__catedraApp.state.view),'oral');assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));}
await p.evaluate(()=>window.__catedraGoView('simulados'));assert.equal(await p.evaluate(()=>window.__catedraApp.state.view),'simulados');await p.evaluate(()=>window.__catedraApp.setSimAba({currentTarget:{dataset:{v:'registro'}}}));await p.getByText('Raio-X do simulado',{exact:true}).waitFor();console.log(motor+': menu ordenado, acessos separados, fases, estados ativos e destinos antigos passaram.');
}finally{await browser.close();srv.close();}
