import assert from 'node:assert/strict';import {iniciarServidor,lancarNavegador} from './_infra.mjs';
const {srv,url}=await iniciarServidor(process.cwd(),+(process.env.CT_PORT||9374));const {browser,motor}=await lancarNavegador();
try{const p=await browser.newPage({viewport:{width:390,height:844}}),erros=[];p.on('pageerror',e=>erros.push(e.message));await p.goto(url+'/__semente');await p.evaluate(()=>{localStorage.clear();localStorage.setItem('catedra:auth','1');localStorage.setItem('catedra:onboarded','1');});await p.goto(url+'/Catedra.dc.html');await p.waitForFunction(()=>window.__catedraApp);
 // Camada auth real com transporte inerte: prova lápides e merge sem qualquer IA ou servidor.
 await p.evaluate(()=>{window.CATEDRA_SUPABASE={url:'http://teste.invalido',key:'chave-de-teste'};window.supabase={createClient:()=>({auth:{onAuthStateChange:()=>{},getSession:()=>new Promise(()=>{})},from:()=>({select:()=>({eq:()=>({maybeSingle:()=>new Promise(()=>{})})}),upsert:()=>({then:()=>new Promise(()=>{})})})})};});await p.addScriptTag({url:url+'/auth.js'});
 await p.evaluate(()=>{const a=window.__catedraApp;a.setState({view:'edital',editalAtivo:'ed-principal',editais:[{id:'ed-principal',nome:'TJ A',discs:{'Direito Civil':{peso:2,questoes:10}},up:10},{id:'b',nome:'TJ B',discs:{'Direito Civil':{peso:3,questoes:20}},up:10}],edital:[{disc:'Direito Civil',peso:2,questoes:10,topics:[{name:'Obrigações',done:true,eds:['ed-principal','b']}]}],sessions:[{id:'s',disc:'Direito Civil',min:30}],flashcards:[{id:'f',front:'Frente',back:'Verso',disc:'Direito Civil'}]});a._saveSessions(a.state.sessions);a._saveFC(a.state.flashcards);a._salvarAgora();});
 const preservado=await p.evaluate(()=>{const s=window.__catedraApp.state;return JSON.stringify({sessions:s.sessions,fc:s.flashcards,topics:s.edital[0].topics});});
 // A fixture de transporte mantém login pendente; libera somente a interface já autenticada localmente.
 await p.evaluate(()=>{const g=document.getElementById('catedra-auth-gate');if(g)g.remove();[...document.body.children].forEach(n=>{n.removeAttribute('inert');n.removeAttribute('aria-hidden');});});
 p.once('dialog',d=>d.dismiss());await p.getByRole('button',{name:'Remover “TJ A”',exact:true}).click();assert.equal(await p.evaluate(()=>window.__catedraApp.state.editais.length),2);
 p.once('dialog',async d=>{assert.match(d.message(),/TJ A/);await d.accept();});await p.getByRole('button',{name:'Remover “TJ A”',exact:true}).click();await p.getByRole('button',{name:'Desfazer remoção'}).waitFor();
 let r=await p.evaluate(()=>{const a=window.__catedraApp,t=window.CatedraSync._test;return {ids:a.state.editais.map(e=>e.id),ativo:a.state.editalAtivo,peso:a.state.edital[0].peso,tomb:t.tombLoad(),merge:JSON.parse(t.mergeAll({'catedra:editais':JSON.stringify([{id:'ed-principal',nome:'Antigo',up:99}])},{'catedra:editais':localStorage.getItem('catedra:editais')})['catedra:editais'])};});assert.deepEqual(r.ids,['b']);assert.equal(r.ativo,'b');assert.equal(r.peso,3);assert.ok(r.tomb.arr['catedra:editais']['ed-principal']);assert.ok(!r.merge.some(e=>e.id==='ed-principal'));
 // A ação de desfazer pertence à área e à conta em que a remoção ocorreu.
 await p.evaluate(()=>{const a=window.__catedraApp;window.__undoTeste=a.state.concursoRemovido;a._trocarArea('saude');});await p.waitForFunction(()=>window.__catedraApp.state.areaEstudo==='saude');const saudeAntes=await p.evaluate(()=>JSON.stringify(window.__catedraApp.state.editais));assert.equal(await p.evaluate(()=>window.__catedraApp.state.concursoRemovido),null);await p.evaluate(()=>{const a=window.__catedraApp;a.setState({concursoRemovido:window.__undoTeste});a.desfazerRemoverConcurso();});assert.equal(await p.evaluate(()=>JSON.stringify(window.__catedraApp.state.editais)),saudeAntes);await p.evaluate(()=>window.__catedraApp._trocarArea('juridica'));await p.waitForFunction(()=>window.__catedraApp.state.areaEstudo==='juridica'&&window.__catedraApp.state.editais.some(e=>e.id==='b'));assert.equal(await p.evaluate(()=>window.__catedraApp.state.editais.some(e=>e.id==='ed-principal')),false);await p.evaluate(()=>window.__catedraApp.setState({concursoRemovido:window.__undoTeste}));
 await p.getByRole('button',{name:'Desfazer remoção'}).click();await p.getByRole('button',{name:'Remover “TJ A”',exact:true}).waitFor();assert.equal(await p.evaluate(()=>!!((window.CatedraSync._test.tombLoad().arr||{})['catedra:editais']||{})['ed-principal']),false);
 for(const nome of ['TJ A','TJ B']){p.once('dialog',d=>d.accept());await p.getByRole('button',{name:'Remover “'+nome+'”',exact:true}).click();await p.waitForFunction(n=>!window.__catedraApp.state.editais.some(e=>e.nome===n),nome);}
 assert.equal(await p.evaluate(()=>window.__catedraApp._editaisComMigracao().length),0);assert.equal(await p.evaluate(()=>{const s=window.__catedraApp.state;return JSON.stringify({sessions:s.sessions,fc:s.flashcards,topics:s.edital[0].topics});}),preservado);
 await p.reload();await p.waitForFunction(()=>window.__catedraApp);assert.equal(await p.evaluate(()=>window.__catedraApp._editaisComMigracao().length),0);assert.equal(await p.evaluate(()=>window.__catedraApp.state.sessions.length),1);assert.equal(await p.evaluate(()=>window.__catedraApp.state.flashcards.length),1);assert.deepEqual(erros,[]);console.log(motor+': remoção, desfazer, lápides, merge e último concurso sem perda passaram.');
}finally{await browser.close();srv.close();}
